### PR TITLE
[FEATURE] Add tasks to do in Search

### PR DESCRIPTION
**Pull request by aceofspades19**
Tried to follow the images provided as closely as possible for this issue.
Need translations added for other languages at the very least. 
Lots of additions so I expect criticism and changes :)

### CODE REVIEW

**Comment by eduayme** [comment]
Uou Nice @aceofspades19! The only thing you should do is adding all screenshots of the final design so it is easier to understand and approve your changes.

**Comment by eduayme** [comment]
The only thing you should do is adding screenshots of your final design so it is easier to understand and approve your changes.

**Comment by aceofspades19** [comment]
image
image
Thank you, @eduayme 
Here are the screenshots

**Comment by aceofspades19** [comment]
Made a couple small css tweaks that I noticed were wrong

**Pull request merged**
