### PR TITLE
Min search id length message fix

### PR DESCRIPTION
**Pull request by gyaaniguy**
Search id validation message fix. Changed from require 2 chars to 3 chars.

### CODE REVIEW

**Comment by eduayme** [comment]
There is no problem with the 2 minimum length message. This pull request makes no sense.

**Comment by gyaaniguy** [comment]
The message appears even when there are 2 chars. Validation rule States minimum 3 characters. While the message States 2 characters

**Comment by eduayme** [comment]
You should first open an issue with the problem, describing it. Add a screenshot of this problem. 

The only case I can think about now is the name in the register. And the minimum characters are 2 so the message it is perfect as it is.

**Comment by gyaaniguy** [comment]
Got it. Felt it was too small an issue for a bug report. lesson learned.
I have created an issue https://github.com/eduayme/RescueApp/issues/97

**Pull request closed without merging**
